### ISSUE TITLE
Towards Unified Editing

### ISSUE THREAD

**Issue by sameersingh** [wolfe-pack/moro#51]
Meta issue to track all the issues for unified fluid editing.

Multiple features to create the next generation of unified editing:
- [x] All ACE editing, #48 
- [x] cursors moves fluidly between cells, done.
- [x] change modes using keyboard, done: #50 
- [x] Split/Merge/Delete: currently only delete supported, #52 
- [ ] Allow line numbers to continue? Might not be important or easy
- [x] Layout and formatting.

**Comment by sameersingh** [comment]
This seems pretty much done.
